# Generated by Django 4.2.2 on 2023-08-10 16:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Marka', models.CharField(max_length=100)),
                ('Seri', models.CharField(max_length=100)),
                ('Model', models.CharField(max_length=100)),
                ('Yıl', models.IntegerField()),
                ('Kilometre', models.FloatField()),
                ('VitesTipi', models.CharField(max_length=50)),
                ('YakıtTipi', models.CharField(max_length=50)),
                ('KasaTipi', models.CharField(max_length=50)),
                ('MotorHacmi', models.FloatField()),
                ('MotorGücü', models.FloatField()),
                ('Çekiş', models.CharField(max_length=50)),
                ('OrtYakıtTüketimi', models.FloatField()),
                ('YakıtDeposu', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='KasaTipi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kasa_tipi', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Marka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_adi', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Seri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seri_adi', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VitesTipi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vites_tipi', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='YakıtTipi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yakit_tipi', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Çekiş',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('çekiş_tipi', models.CharField(max_length=50)),
            ],
        ),
    ]
