# Generated by Django 4.2.2 on 2023-09-08 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('priceForm', '0003_alter_arac_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arac',
            name='OrtYakıtTüketimi',
        ),
        migrations.RemoveField(
            model_name='arac',
            name='YakıtDeposu',
        ),
    ]
