# Generated by Django 4.2.2 on 2023-09-09 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('priceForm', '0004_remove_arac_ortyakıttüketimi_remove_arac_yakıtdeposu'),
    ]

    operations = [
        migrations.AddField(
            model_name='arac',
            name='TahminiFiyat',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
